---
title: "R Notebook"
output: html_notebook
---


```{r}
packages <- c('dplyr','ggplot2','tidyverse','tidyr','lubridate','readr','skimr','naniar')


install_package <- packages %in% row.names(installed.packages())
if (any (install_package ==  FALSE))
  install.packages(packages[!install_package])

sapply(packages, require, character.only = TRUE)

```

```{r}

# Loading the data set (step)

vaccine_data <- read.csv("COVID_Vaccine_data.csv")

head (vaccine_data)

str(vaccine_data)

```

```{r}
dim (vaccine_data)

```
```{r}

vaccine_data_copy <- vaccine_data[,1:13]

colnames(vaccine_data_copy)

```


```{r}

# Total NA in the entire data set

sum(is.na(vaccine_data_copy))
prod(dim(vaccine_data_copy))

# % of NA's in entire dataset

(sum(is.na(vaccine_data_copy)) / prod(dim(vaccine_data_copy))) * 100



```

```{r}
# NA's per feature can also be visualised as below


vis_miss(vaccine_data_copy)

```


```{r}
#total number of NA per feature

data.frame("Total_NA" = colSums(is.na(vaccine_data_copy)))

```

```{r}

#proportions of NA per feature

data.frame("Percentage_of_NA"=colSums(is.na(vaccine_data_copy))/dim(vaccine_data_copy)[1]) %>%
  round(3) * 100

```
```{r}
unique(vaccine_data_copy$country)


```


```{r}

# ISO Code is usually 3 digit country code which are developed and maintained by the United Nations Statistics Division

vaccine_data_copy %>%
  select (country,iso_code) %>%
  unique() %>%
  filter (nchar(iso_code) > 3)

```

```{r}

# United kingdom is a Sovereign country in North West of Europe, which consist of 4 countries  England, Scotland, Wales and Northern Ireland. 
# Let us find if we already have United kingdom and Cyprus separately 

vaccine_data_copy %>%
  select (country,iso_code) %>%
  filter (country %in% c("United Kingdom","Cyprus"))%>%
  unique()
  

```


```{r}
#Data Cleaning
#There are few steps in this section:

#As shown by .head() method, our data obviously contains missing values, so we'll need to deal with it somehow
#Some of the country names appeared in the dataset, does not represent a single country (constituent countries) and also the union territories
#Multiple vaccines are updated in a single row and needs to be separated

```


```{r}
# Handling the missing values

vaccine_data_copy[is.na(vaccine_data_copy)] = 0

sum(is.na(vaccine_data_copy))

# there are no more NA in the data set

```


```{r}

# Removing the UK soviet countries
# I also consider to eliminate Gibraltar, Isle of Man, Cayman Islands, Falkland Islands, Guernsey, Saint Helena, Turks and Caicos Islands (UK pertinence), Faeroe Islands (Denmark pertinence).

remove_countries = c('England','Northern Ireland','Scotland','Wales','Falkland Islands','Faeroe Islands','Isle of Man','Cayman Islands','Saint Helena','Saint Lucia','Saint Vincent and the Grenadines','Saint Kitts and Nevis')


vaccine_data_copy <- vaccine_data_copy %>%
  filter (!country %in% remove_countries) 

unique(vaccine_data_copy$country)

```

```{r}
# Below the Vaccines use world wide

vaccine_val<- data.frame(unique(vaccine_data_copy$vaccines))
uniq_vaccine<- vector()

for (i in vaccine_val){
  for (j in strsplit(i, ",")){
    uniq_vaccine<- c(uniq_vaccine, str_replace_all(j," ",""))
  } 
}

vaccine_given<- unique(uniq_vaccine)
print(vaccine_given)


```


```{r}

vaccine_data_val <- data.frame(matrix(ncol = length(vaccine_given), nrow = 0))
for (i in vaccine_data_copy$vaccines){
 #vaccine_data_val<- rbind(vaccine_data_val, Vectorize(grepl, USE.NAMES = TRUE)(vaccine_given, i))
  vaccine_data_val<- rbind(vaccine_data_val, Vectorize(grepl, USE.NAMES = TRUE)(vaccine_given, str_replace_all(i," ","")))
}
#colnames(vaccine_data_val) <- vaccine_given
colnames(vaccine_data_val) <- paste0("vacc_",unique(uniq_vaccine))
colnames(vaccine_data_val)
vaccine_data_val[vaccine_data_val == TRUE] = 1
vaccine_data_val[vaccine_data_val == FALSE] =0
```


```{r}
vaccine_data_copy

```


```{r}
vaccine_data_val
```

```{r}
vaccine_data_copy<- cbind (vaccine_data_copy, vaccine_data_val)
vaccine_data_copy
```


```{r}

#Dropping the vaccine column

vaccine_data_copy<- vaccine_data_copy[,!(colnames(vaccine_data_copy) == "vaccines")]

```


```{r}
vaccine_data_copy
```

```{r}
# Data Visualization

n <- vaccine_data_copy%>%
  select(starts_with("vacc_"))

```


```{r}
colSums(n)
gather(key="key", value = "value",colSums(n))

```




